#define FIELD_SIZE 10
#define TICK 1
#define STARTING_DOTS_COUNT 10
#define SCORE_MODIFIER_NORMAL 1
#define SCORE_MODIFIER_BONUS 1.2
#define MAXIMUM_DOT_COUNT_INITIAL 70
#define MAXIMUM_DOT_COUNT_LIMIT 80
#define MAXIMUM_DOT_COUNT_STEP 2